=== Devillzify/Programacion/Celler/celler.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="celler">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="productes"/>
                <xs:element ref="clients"/>
                <xs:element ref="factures"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="productes">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="12" maxOccurs="12"  ref="producte"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="producte">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="codi" use="required" type="tipo_codi_producte"/>
                    <xs:attribute name="preu" use="required" type="xs:float"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipo_codi_producte">
        <xs:restriction base="xs:ID">
            <xs:pattern value="[BRT][1235]"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="clients">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="client"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="client">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nom" type="nom_i_cognoms"/>
                <xs:element name="cognoms" type="nom_i_cognoms"/>
                <xs:element ref="contacte"/>
            </xs:sequence>
            <xs:attribute name="codi" use="required" type="xs:ID"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="nom_i_cognoms">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][a-z]+( [A-Z][a-z]+)?"/>
        </xs:restriction>
    </xs:simpleType>



    <xs:element name="contacte">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="telefon"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="telefon">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="base_telefon">
                    <xs:attribute name="tipus" use="required" type="tipus_telefon"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tipus_telefon">
        <xs:restriction base="xs:string">
            <xs:enumeration value="fix"/>
            <xs:enumeration value="mobil"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="base_telefon">
        <xs:restriction base="xs:string">
            <xs:pattern value="[6789]\d{2} \d{3} \d{3}"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:element name="factures">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" ref="factura"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:element name="factura">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="comprador"/>
                <xs:element maxOccurs="unbounded" ref="unitats"/>
            </xs:sequence>
            <xs:attribute name="numero" use="required" type="tipo_numero_factura"/>
        </xs:complexType>
    </xs:element>

<xs:simpleType name="tipo_numero_factura">
    <xs:restriction base="xs:ID">
        <xs:pattern value="F\d{6}"/>
    </xs:restriction>
</xs:simpleType>

    <xs:element name="comprador">
        <xs:complexType>
            <xs:attribute name="codi" use="required" type="xs:IDREF"/>
        </xs:complexType>
    </xs:element>


    <xs:element name="unitats">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:integer">
                    <xs:attribute name="codi" use="required" type="xs:IDREF"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Devillzify/Programacion/Celler/celler.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xsl" href="celler.xsl"?>
<celler xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="celler.xsd">
    <productes>
        <producte codi="B1" preu="1.50">Vino Blanco de 1 litro(s)</producte>
        <producte codi="B2" preu="2.50">Vino Blanco de 2 litro(s)</producte>
        <producte codi="B3" preu="3.50">Vino Blanco de 3 litro(s)</producte>
        <producte codi="B5" preu="5.50">Vino Blanco de 5 litro(s)</producte>
        <producte codi="R1" preu="1.50">Vino Rosado de 1 litro(s)</producte>
        <producte codi="R2" preu="2.50">Vino Rosado de 2 litro(s)</producte>
        <producte codi="R3" preu="3.50">Vino Rosado de 3 litro(s)</producte>
        <producte codi="R5" preu="5.50">Vino Rosado de 5 litro(s)</producte>
        <producte codi="T1" preu="1.50">Vino Tinto de 1 litro(s)</producte>
        <producte codi="T2" preu="2.50">Vino Tinto de 2 litro(s)</producte>
        <producte codi="T3" preu="3.50">Vino Tinto de 3 litro(s)</producte>
        <producte codi="T5" preu="5.50">Vino Tinto de 5 litro(s)</producte>
    </productes>
    <clients>
        <client codi="C00001">
            <nom>Adolfo</nom>
            <cognoms>Salazar Guerrero</cognoms>
            <contacte>
                <telefon tipus="mobil">711 767 644</telefon>
                <telefon tipus="fix">904 988 382</telefon>
            </contacte>
        </client>
        <client codi="C00002">
            <nom>Africa</nom>
            <cognoms>Simon Gonzalez</cognoms>
            <contacte>
                <telefon tipus="fix">890 285 002</telefon>
                <telefon tipus="fix">873 130 999</telefon>
                <telefon tipus="fix">840 256 905</telefon>
            </contacte>
        </client>
        <client codi="C00003">
            <nom>Pascual</nom>
            <cognoms>Bravo Menendez</cognoms>
            <contacte>
                <telefon tipus="mobil">798 236 123</telefon>
                <telefon tipus="mobil">765 421 336</telefon>
                <telefon tipus="mobil">634 920 535</telefon>
            </contacte>
        </client>
        <client codi="C00004">
            <nom>Mateo</nom>
            <cognoms>Marti Perez</cognoms>
            <contacte>
                <telefon tipus="mobil">793 901 542</telefon>
                <telefon tipus="mobil">695 409 648</telefon>
            </contacte>
        </client>
        <client codi="C00005">
            <nom>Ricardo</nom>
            <cognoms>Segura Costa</cognoms>
            <contacte>
                <telefon tipus="mobil">736 403 329</telefon>
            </contacte>
        </client>
        <client codi="C00006">
            <nom>Lorena</nom>
            <cognoms>Marcos Morales</cognoms>
            <contacte>
                <telefon tipus="fix">878 764 873</telefon>
                <telefon tipus="mobil">684 617 404</telefon>
            </contacte>
        </client>
        <client codi="C00007">
            <nom>Moises</nom>
            <cognoms>Carrillo Guerrero</cognoms>
            <contacte>
                <telefon tipus="fix">948 709 433</telefon>
            </contacte>
        </client>
        <client codi="C00008">
            <nom>Victoriano</nom>
            <cognoms>Calvo</cognoms>
            <contacte>
                <telefon tipus="fix">823 952 457</telefon>
                <telefon tipus="mobil">705 674 190</telefon>
            </contacte>
        </client>
        <client codi="C00009">
            <nom>Adolfo</nom>
            <cognoms>Saez Diaz</cognoms>
            <contacte>
                <telefon tipus="fix">972 746 797</telefon>
            </contacte>
        </client>
        <client codi="C00010">
            <nom>Justo</nom>
            <cognoms>Marcos Caballero</cognoms>
            <contacte>
                <telefon tipus="fix">862 796 668</telefon>
                <telefon tipus="mobil">660 884 131</telefon>
            </contacte>
        </client>
    </clients>
    <factures>
        <factura numero="F000001">
            <comprador codi="C00010"/>
            <unitats codi="B3">1</unitats>
            <unitats codi="B5">5</unitats>
            <unitats codi="R5">2</unitats>
            <unitats codi="T3">1</unitats>
            <unitats codi="T5">1</unitats>
        </factura>
        <factura numero="F000002">
            <comprador codi="C00005"/>
            <unitats codi="B2">3</unitats>
            <unitats codi="B3">5</unitats>
            <unitats codi="R1">4</unitats>
            <unitats codi="T1">1</unitats>
            <unitats codi="T2">3</unitats>
        </factura>
        <factura numero="F000003">
            <comprador codi="C00004"/>
            <unitats codi="B1">2</unitats>
            <unitats codi="B2">3</unitats>
            <unitats codi="R1">1</unitats>
            <unitats codi="R2">4</unitats>
            <unitats codi="R5">3</unitats>
            <unitats codi="T1">1</unitats>
            <unitats codi="T2">3</unitats>
            <unitats codi="T5">4</unitats>
        </factura>
        <factura numero="F000004">
            <comprador codi="C00007"/>
            <unitats codi="B1">1</unitats>
            <unitats codi="B2">5</unitats>
            <unitats codi="B3">1</unitats>
            <unitats codi="R1">5</unitats>
            <unitats codi="R2">1</unitats>
            <unitats codi="R5">1</unitats>
            <unitats codi="T5">1</unitats>
        </factura>
        <factura numero="F000005">
            <comprador codi="C00010"/>
            <unitats codi="B1">2</unitats>
            <unitats codi="B3">3</unitats>
            <unitats codi="R1">5</unitats>
            <unitats codi="R3">3</unitats>
            <unitats codi="R5">2</unitats>
            <unitats codi="T1">5</unitats>
        </factura>
        <factura numero="F000006">
            <comprador codi="C00003"/>
            <unitats codi="B1">2</unitats>
            <unitats codi="B2">4</unitats>
            <unitats codi="R1">4</unitats>
            <unitats codi="R5">4</unitats>
            <unitats codi="T1">3</unitats>
            <unitats codi="T5">5</unitats>
        </factura>
        <factura numero="F000007">
            <comprador codi="C00005"/>
            <unitats codi="B2">2</unitats>
            <unitats codi="B3">5</unitats>
            <unitats codi="B5">4</unitats>
            <unitats codi="R1">5</unitats>
            <unitats codi="R5">4</unitats>
            <unitats codi="T2">5</unitats>
        </factura>
        <factura numero="F000008">
            <comprador codi="C00006"/>
            <unitats codi="B5">1</unitats>
            <unitats codi="R1">5</unitats>
            <unitats codi="R2">4</unitats>
            <unitats codi="R5">3</unitats>
            <unitats codi="T2">3</unitats>
            <unitats codi="T3">1</unitats>
            <unitats codi="T5">2</unitats>
        </factura>
        <factura numero="F000009">
            <comprador codi="C00006"/>
            <unitats codi="B1">3</unitats>
            <unitats codi="B3">5</unitats>
            <unitats codi="R2">4</unitats>
            <unitats codi="R5">2</unitats>
            <unitats codi="T1">3</unitats>
            <unitats codi="T5">1</unitats>
        </factura>
        <factura numero="F000010">
            <comprador codi="C00006"/>
            <unitats codi="R1">4</unitats>
            <unitats codi="R2">2</unitats>
        </factura>
        <factura numero="F000011">
            <comprador codi="C00004"/>
            <unitats codi="B1">4</unitats>
            <unitats codi="B3">2</unitats>
            <unitats codi="B5">4</unitats>
            <unitats codi="R1">1</unitats>
            <unitats codi="R2">4</unitats>
            <unitats codi="R3">5</unitats>
            <unitats codi="R5">4</unitats>
            <unitats codi="T3">5</unitats>
            <unitats codi="T5">4</unitats>
        </factura>
        <factura numero="F000012">
            <comprador codi="C00006"/>
            <unitats codi="B1">3</unitats>
            <unitats codi="B2">5</unitats>
            <unitats codi="R3">3</unitats>
            <unitats codi="T1">5</unitats>
            <unitats codi="T3">4</unitats>
        </factura>
        <factura numero="F000013">
            <comprador codi="C00009"/>
            <unitats codi="B1">4</unitats>
            <unitats codi="B2">1</unitats>
            <unitats codi="B3">4</unitats>
            <unitats codi="R2">4</unitats>
            <unitats codi="R5">5</unitats>
            <unitats codi="T1">3</unitats>
            <unitats codi="T2">4</unitats>
            <unitats codi="T5">1</unitats>
        </factura>
        <factura numero="F000014">
            <comprador codi="C00010"/>
            <unitats codi="B2">1</unitats>
            <unitats codi="B5">5</unitats>
            <unitats codi="R2">1</unitats>
            <unitats codi="R5">3</unitats>
            <unitats codi="T3">5</unitats>
        </factura>
        <factura numero="F000015">
            <comprador codi="C00002"/>
            <unitats codi="B1">3</unitats>
            <unitats codi="B2">2</unitats>
            <unitats codi="B5">1</unitats>
            <unitats codi="R2">4</unitats>
            <unitats codi="R3">1</unitats>
            <unitats codi="R5">5</unitats>
        </factura>
        <factura numero="F000016">
            <comprador codi="C00010"/>
            <unitats codi="B1">2</unitats>
            <unitats codi="B3">3</unitats>
            <unitats codi="B5">5</unitats>
            <unitats codi="R1">3</unitats>
            <unitats codi="R3">4</unitats>
            <unitats codi="T1">5</unitats>
            <unitats codi="T5">3</unitats>
        </factura>
        <factura numero="F000017">
            <comprador codi="C00006"/>
            <unitats codi="B3">4</unitats>
            <unitats codi="R5">1</unitats>
            <unitats codi="T1">3</unitats>
